# Generated by Django 2.2.21 on 2021-05-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0009_auto_20190202_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback_model',
            name='uregsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_Controller.Userregisters_Model'),
        ),
        migrations.AlterField(
            model_name='userwateranalysis_model',
            name='uregid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users_Controller.Userregisters_Model'),
        ),
    ]
